In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm #need to install statsmodels
import statsmodels.formula.api as smf
from statsmodels.stats.anova import anova_lm
import dataframe_image as dfi

In [39]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 160)

In [40]:
df_assess = pd.read_csv("data/cleaned/final_assessment.csv")
df_grades = pd.read_csv("data/cleaned/grades.csv")
df_status = pd.read_csv("data/cleaned/status.csv")
df_intake = pd.read_csv("data/cleaned/intake_form.csv")

In [41]:
df_intake

,id,recruitment_source,dsc_affiliation,math_affiliation,class_standing,stats_courses_taken,stats_confidence,chebyshev_familiarity,python_skill_level
0,0,DSC 140B,major,neither,Second year,"MATH 180A, MATH 181A",4,2,5
1,1,DSC 140B,major,neither,Third year,MATH 180A,4,3,5
2,3,DSC 140B,major,neither,Third year,MATH 183,4,3,4
3,6,DSC 140B,major,neither,Second year,MATH 183,3,1,4
4,9,DSC 140B,major,major,Third year,MATH 183,4,2,4
5,11,DSC 140B,major,neither,Second year,MATH 183,3,1,4
6,12,DSC 140B,major,neither,Third year,MATH 183,4,4,4
7,15,DSC 80,major,neither,Third year (first year transfer),MATH 183,3,1,4
8,20,DSC 180,major,neither,Third year transfer,MATH 183,2,2,4
9,24,DSC 180,major,neither,Fourth year (second year transfer),"MATH 180A, MATH 181A, MATH 183",5,5,5
10,26,DSC 180,minor,major,Fourth year,MATH 183,3,2,4
11,27,DSC 180,major,major,Fourth year,"MATH 180A, MATH 181A",4,4,4
12,28,DSC 40B,major,neither,Second year,None of the above,2,1,3
13,29,DSC 180,major,neither,third year transfer,"MATH 180A, MATH 181A",2,2,2
14,30,DSC 120,major,neither,Third year,ECON 120A,3,3,4
15,33,DSC 140B,major,neither,Third year,MATH 183,4,4,5
16,38,DSC 140B,major,neither,Fourth year (second year transfer),ECON 120A,4,3,3
17,40,DSC 20,major,neither,First year,None of the above,3,4,4
18,41,DSC 20,major,neither,First year,None of the above,1,2,3
19,46,DSC 10,neither,major,First year,None of the above,2,1,2
20,48,DSC 20,major,neither,First year,ECON 120A,3,3,2
21,51,DSC 10,minor,major,First year,None of the above,2,2,2
22,53,DSC 10,neither,neither,First year,None of the above,1,1,2
23,56,DSC 20,major,neither,First year,None of the above,3,4,3
24,58,DSC 20,major,neither,First year,None of the above,3,4,3
25,61,DSC 10,neither,neither,First year,None of the above,2,2,2
26,63,DSC 10,minor,neither,First year,None of the above,4,1,3
27,64,DSC 190,major,major,Fourth year,"MATH 180A, MATH 181A",5,3,5
28,66,DSC 10,neither,neither,Fourth year,None of the above,5,2,1
29,80,DSC 190,major,neither,Third year,"MATH 180A, MATH 183",5,1,5
30,88,DSC 10,minor,major,First year,None of the above,4,4,4

## Merge two dataframes(grades and status) by id, create coding and handwritten binary columns for b1 vs b2 test. I got rid of section 4 for now since they will affect both b1(coefficient of coding) and b2(coefficient of handwritten).

In [42]:
df_status = df_status[df_status['completed'] == 1]

sample = df_grades.merge(df_status[["id", "section"]], on="id", how="inner")

sample['coding'] =  ((sample['section'] == 2) | (sample['section'] == 4)).astype(int) #(yes,1), (no,0)
sample['handwritten'] =  ((sample['section'] == 3) | (sample['section'] == 4)).astype(int) #(yes,1), (no,0)
#sample_filter = sample[(sample['coding'] == 0) | (sample['handwritten'] == 0)]
sample

    id  coding_score  handwritten_score  final_score  final_score_adj  section  coding  handwritten
0    0           NaN                NaN     0.737705         0.586066        1       0            0
1    1      0.928571                NaN     0.754098         0.610656        2       1            0
2    3      0.857143                1.0     0.836066         0.479508        4       1            1
3    6           NaN                1.0     0.508197         0.200820        3       0            1
4    9      0.904764                NaN     0.672131         0.471311        2       1            0
5   11      0.928571                1.0     0.918033         0.319672        4       1            1
6   12           NaN                NaN     0.098361         0.000000        1       0            0
7   15      1.000000                1.0     0.344262         0.159836        4       1            1
8   20           NaN                NaN     0.573770         0.303279        1       0            0
9   24           NaN                NaN     1.000000         0.754098        1       0            0
10  26           NaN                1.0     0.737705         0.442623        3       0            1
11  27      1.000000                1.0     0.540984         0.385246        4       1            1
12  28           NaN                NaN     0.557377         0.286885        1       0            0
13  29      1.000000                NaN     0.672131         0.479508        2       1            0
14  30           NaN                1.0     0.852459         0.442623        3       0            1
15  33      0.904764                NaN     0.540984         0.311475        2       1            0
16  38           NaN                1.0     0.721311         0.430328        3       0            1
17  40           NaN                NaN     0.622951         0.229508        1       0            0
18  41      1.000000                NaN     0.508197         0.155738        2       1            0
19  46           NaN                1.0     0.606557         0.364754        3       0            1
20  48           NaN                NaN     0.442623         0.303279        1       0            0
21  51      0.785714                1.0     0.918033         0.590164        4       1            1
22  53      1.000000                NaN     0.622951         0.405738        2       1            0
23  56           NaN                NaN     0.786885         0.557377        1       0            0
24  58           NaN                1.0     0.459016         0.168033        3       0            1
25  61      1.000000                NaN     1.000000         0.479508        2       1            0
26  63      1.000000                1.0     0.721311         0.196721        4       1            1
27  64           NaN                NaN     0.868852         0.819672        1       0            0
28  66           NaN                1.0     1.000000         0.778689        3       0            1
29  80           NaN                NaN     0.737705         0.520492        1       0            0
30  88           NaN                NaN     0.131148        -0.032787        1       0            0

## Linear model for final_score = bias(section1) + b1 * coding + b2 * handwritten + b3 * (coding*written)

In [43]:
res = smf.ols(
    formula='final_score ~ coding * handwritten',
    data=sample
).fit()

print(res.summary())

s1 = res.summary2()
df_model = s1.tables[0]
df_coef  = s1.tables[1]
dfi.export(df_coef,  "data/statistic_analysis_outputs/final_separate.png", table_conversion="chrome", dpi = 300)

                            OLS Regression Results
==============================================================================
Dep. Variable:            final_score   R-squared:                       0.049
Model:                            OLS   Adj. R-squared:                 -0.056
Method:                 Least Squares   F-statistic:                    0.4666
Date:                Wed, 25 Feb 2026   Prob (F-statistic):              0.708
Time:                        16:39:03   Log-Likelihood:                 3.5034
No. Observations:                  31   AIC:                            0.9932
Df Residuals:                      27   BIC:                             6.729
Df Model:                           3
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              0.5961      0.070      8.538      0.000       0.453       0.739
coding                 0.0854      0.112      0.763      0.452      -0.144       0.315
handwritten            0.1018      0.112      0.909      0.371      -0.128       0.331
coding:handwritten    -0.0702      0.171     -0.411      0.684      -0.420       0.280
==============================================================================
Omnibus:                        1.233   Durbin-Watson:                   1.864
Prob(Omnibus):                  0.540   Jarque-Bera (JB):                0.934
Skew:                          -0.417   Prob(JB):                        0.627
Kurtosis:                       2.828   Cond. No.                         6.16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Linear model is final score = bias(section 1) + b1 * (handwritten + coding) + b2 * (coding * written)

In [44]:
res2 = smf.ols(
    formula='final_score ~ I(coding + handwritten) + coding:handwritten',
    data=sample
).fit()

print(res2.summary())
#anova_results = anova_lm(model2, model1)
s2 = res2.summary2()
df_model2 = s2.tables[0]
df_coef2  = s2.tables[1]
dfi.export(df_coef2,  "data/statistic_analysis_outputs/final_combine.png", table_conversion="chrome", dpi = 300)

                            OLS Regression Results
==============================================================================
Dep. Variable:            final_score   R-squared:                       0.049
Model:                            OLS   Adj. R-squared:                 -0.019
Method:                 Least Squares   F-statistic:                    0.7162
Date:                Wed, 25 Feb 2026   Prob (F-statistic):              0.497
Time:                        16:39:04   Log-Likelihood:                 3.4933
No. Observations:                  31   AIC:                           -0.9867
Df Residuals:                      28   BIC:                             3.315
Df Model:                           2
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                   0.5961      0.069      8.692      0.000       0.456       0.737
I(coding + handwritten)     0.0936      0.092      1.021      0.316      -0.094       0.281
coding:handwritten         -0.0702      0.168     -0.418      0.679      -0.414       0.273
==============================================================================
Omnibus:                        1.199   Durbin-Watson:                   1.865
Prob(Omnibus):                  0.549   Jarque-Bera (JB):                0.917
Skew:                          -0.412   Prob(JB):                        0.632
Kurtosis:                       2.820   Cond. No.                         6.58
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Anova Test between two models

In [45]:
anova_results = sm.stats.anova_lm(res2, res)
print(anova_results)
dfi.export(
    anova_results,
    "data/statistic_analysis_outputs/final_anova.png",
    table_conversion="chrome",
    dpi = 300
)

   df_resid       ssr  df_diff   ss_diff         F    Pr(>F)
0      28.0  1.448797      0.0       NaN       NaN       NaN
1      27.0  1.447856      1.0  0.000941  0.017541  0.895617

## Linear model for adjusted final score = bias(section1) + b1 * coding + b2 * handwritten + b3 * (coding*written)

In [46]:
res3 = smf.ols(
    formula='final_score_adj ~ coding * handwritten',
    data=sample
).fit()

print(res3.summary())

s3 = res3.summary2()
df_model3 = s3.tables[0]
df_coef3  = s3.tables[1]
dfi.export(df_coef3,  "data/statistic_analysis_outputs/final_adj_separate.png", table_conversion="chrome", dpi = 300)

                            OLS Regression Results
==============================================================================
Dep. Variable:        final_score_adj   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                 -0.100
Method:                 Least Squares   F-statistic:                   0.09218
Date:                Wed, 25 Feb 2026   Prob (F-statistic):              0.964
Time:                        16:39:07   Log-Likelihood:                 5.3014
No. Observations:                  31   AIC:                            -2.603
Df Residuals:                      27   BIC:                             3.133
Df Model:                           3
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              0.3934      0.066      5.972      0.000       0.258       0.529
coding                 0.0228      0.106      0.216      0.831      -0.194       0.240
handwritten            0.0105      0.106      0.100      0.921      -0.206       0.227
coding:handwritten    -0.0716      0.161     -0.445      0.660      -0.402       0.259
==============================================================================
Omnibus:                        0.036   Durbin-Watson:                   1.600
Prob(Omnibus):                  0.982   Jarque-Bera (JB):                0.115
Skew:                           0.062   Prob(JB):                        0.944
Kurtosis:                       2.729   Cond. No.                         6.16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Linear model is adjusted final score = bias(section 1) + b1 * (handwritten + coding) + b2 * (coding * written)

In [47]:
res4 = smf.ols(
    formula='final_score_adj ~ I(coding + handwritten) + coding:handwritten',
    data=sample
).fit()

print(res4.summary())
#anova_results = anova_lm(model2, model1)
s4 = res4.summary2()
df_model4 = s4.tables[0]
df_coef4  = s4.tables[1]
dfi.export(df_coef4,  "data/statistic_analysis_outputs/final_adj_combine.png", table_conversion="chrome", dpi = 300)

                            OLS Regression Results
==============================================================================
Dep. Variable:        final_score_adj   R-squared:                       0.010
Model:                            OLS   Adj. R-squared:                 -0.061
Method:                 Least Squares   F-statistic:                    0.1376
Date:                Wed, 25 Feb 2026   Prob (F-statistic):              0.872
Time:                        16:39:08   Log-Likelihood:                 5.2950
No. Observations:                  31   AIC:                            -4.590
Df Residuals:                      28   BIC:                           -0.2881
Df Model:                           2
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                   0.3934      0.065      6.080      0.000       0.261       0.526
I(coding + handwritten)     0.0167      0.086      0.193      0.848      -0.160       0.194
coding:handwritten         -0.0716      0.158     -0.453      0.654      -0.396       0.252
==============================================================================
Omnibus:                        0.025   Durbin-Watson:                   1.608
Prob(Omnibus):                  0.988   Jarque-Bera (JB):                0.124
Skew:                           0.054   Prob(JB):                        0.940
Kurtosis:                       2.709   Cond. No.                         6.58
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Anova Test between two models for adjusted final score

In [48]:
anova_results2 = sm.stats.anova_lm(res4, res3)
print(anova_results2)
dfi.export(
    anova_results2,
    "data/statistic_analysis_outputs/final_adj_anova.png",
    table_conversion="chrome",
    dpi = 300
)

   df_resid       ssr  df_diff   ss_diff        F    Pr(>F)
0      28.0  1.289812      0.0       NaN      NaN       NaN
1      27.0  1.289283      1.0  0.000529  0.01108  0.916946

## Including variables in intake form

In [49]:
new_sample = sample.merge(df_intake, on="id", how="inner")
sample_new = new_sample.drop(columns = ['coding_score', 'handwritten_score', 'section'])
sample_new

,id,final_score,final_score_adj,coding,handwritten,recruitment_source,dsc_affiliation,math_affiliation,class_standing,stats_courses_taken,stats_confidence,chebyshev_familiarity,python_skill_level
0,0,0.737705,0.586066,0,0,DSC 140B,major,neither,Second year,"MATH 180A, MATH 181A",4,2,5
1,1,0.754098,0.610656,1,0,DSC 140B,major,neither,Third year,MATH 180A,4,3,5
2,3,0.836066,0.479508,1,1,DSC 140B,major,neither,Third year,MATH 183,4,3,4
3,6,0.508197,0.200820,0,1,DSC 140B,major,neither,Second year,MATH 183,3,1,4
4,9,0.672131,0.471311,1,0,DSC 140B,major,major,Third year,MATH 183,4,2,4
5,11,0.918033,0.319672,1,1,DSC 140B,major,neither,Second year,MATH 183,3,1,4
6,12,0.098361,0.000000,0,0,DSC 140B,major,neither,Third year,MATH 183,4,4,4
7,15,0.344262,0.159836,1,1,DSC 80,major,neither,Third year (first year transfer),MATH 183,3,1,4
8,20,0.573770,0.303279,0,0,DSC 180,major,neither,Third year transfer,MATH 183,2,2,4
9,24,1.000000,0.754098,0,0,DSC 180,major,neither,Fourth year (second year transfer),"MATH 180A, MATH 181A, MATH 183",5,5,5
10,26,0.737705,0.442623,0,1,DSC 180,minor,major,Fourth year,MATH 183,3,2,4
11,27,0.540984,0.385246,1,1,DSC 180,major,major,Fourth year,"MATH 180A, MATH 181A",4,4,4
12,28,0.557377,0.286885,0,0,DSC 40B,major,neither,Second year,None of the above,2,1,3
13,29,0.672131,0.479508,1,0,DSC 180,major,neither,third year transfer,"MATH 180A, MATH 181A",2,2,2
14,30,0.852459,0.442623,0,1,DSC 120,major,neither,Third year,ECON 120A,3,3,4
15,33,0.540984,0.311475,1,0,DSC 140B,major,neither,Third year,MATH 183,4,4,5
16,38,0.721311,0.430328,0,1,DSC 140B,major,neither,Fourth year (second year transfer),ECON 120A,4,3,3
17,40,0.622951,0.229508,0,0,DSC 20,major,neither,First year,None of the above,3,4,4
18,41,0.508197,0.155738,1,0,DSC 20,major,neither,First year,None of the above,1,2,3
19,46,0.606557,0.364754,0,1,DSC 10,neither,major,First year,None of the above,2,1,2
20,48,0.442623,0.303279,0,0,DSC 20,major,neither,First year,ECON 120A,3,3,2
21,51,0.918033,0.590164,1,1,DSC 10,minor,major,First year,None of the above,2,2,2
22,53,0.622951,0.405738,1,0,DSC 10,neither,neither,First year,None of the above,1,1,2
23,56,0.786885,0.557377,0,0,DSC 20,major,neither,First year,None of the above,3,4,3
24,58,0.459016,0.168033,0,1,DSC 20,major,neither,First year,None of the above,3,4,3
25,61,1.000000,0.479508,1,0,DSC 10,neither,neither,First year,None of the above,2,2,2
26,63,0.721311,0.196721,1,1,DSC 10,minor,neither,First year,None of the above,4,1,3
27,64,0.868852,0.819672,0,0,DSC 190,major,major,Fourth year,"MATH 180A, MATH 181A",5,3,5
28,66,1.000000,0.778689,0,1,DSC 10,neither,neither,Fourth year,None of the above,5,2,1
29,80,0.737705,0.520492,0,0,DSC 190,major,neither,Third year,"MATH 180A, MATH 183",5,1,5
30,88,0.131148,-0.032787,0,0,DSC 10,minor,major,First year,None of the above,4,4,4

In [50]:
sample_new['recruitment_source'].value_counts()
#If I remember it right, class_standing(student's year) is redundant with this feature
#since older students are likely to recruited from a uppertive class

heard_type = {
    'DSC 10': 'Heard_1',
    'DSC 20': 'Heard_1',
    'DSC 30': 'Heard_1',
    'DSC 40A': 'Heard_2',
    'DSC 40B': 'Heard_2',
    'DSC 80': 'Heard_2',
    'DSC 140B': 'Heard_3',
    'CSE 150A': 'Heard_3',
    'CSE 151A': 'Heard_3',
    'DSC 180': 'Heard_3',
    'DSC 100': 'Heard_4',
    'DSC 120': 'Heard_4',
    'DSC 190': 'Heard_4',
}

In [51]:
sample_new['dsc_affiliation'].value_counts()
dsc_type = {
    'major': 'DSC_major',
    'minor': 'DSC_minor',
    'neither': 'DSC_neither',
}

In [52]:
sample_new['math_affiliation'].value_counts()

math_type = {
    'major': 'MATH_major',
    'minor': 'MATH_minor',
    'neither': 'MATH_neither',
}

In [53]:
sample_new['class_standing'].value_counts()

class_standing
First year                            11
Third year                             7
Second year                            4
Fourth year                            4
Fourth year (second year transfer)     2
Third year (first year transfer)       1
Third year transfer                    1
third year transfer                    1
Name: count, dtype: int64

In [54]:
sample_new['stats_courses_taken'].value_counts()

section_type = {
    'MATH 181A': 'Stats_1',
    'MATH 180A': 'Stats_2',
    'ECE 109': 'Stats_2',
    'MAE 108': 'Stats_2',
    'MATH 183': 'Stats_3',
    'MATH 186': 'Stats_3',
    'ECON 120A': 'Stats_3',
    'None of the above': 'Stats_4'
}

In [55]:
def mappings(col, dictionary):
    values = [i.strip() for i in col.split(',')]
    adjust = {dictionary.get(j) for j in values if j in dictionary} #keep unique values
    return ', '.join(adjust)

In [56]:
samples = sample_new.copy()
samples['recruitment_source'] = samples['recruitment_source'].apply(lambda x: mappings(x, heard_type))
samples['stats_courses_taken'] = samples['stats_courses_taken'].apply(lambda x: mappings(x, section_type))
samples['dsc_affiliation'] = samples['dsc_affiliation'].apply(lambda x: mappings(x, dsc_type))
samples['math_affiliation'] = samples['math_affiliation'].apply(lambda x: mappings(x, math_type))
samples

,id,final_score,final_score_adj,coding,handwritten,recruitment_source,dsc_affiliation,math_affiliation,class_standing,stats_courses_taken,stats_confidence,chebyshev_familiarity,python_skill_level
0,0,0.737705,0.586066,0,0,Heard_3,DSC_major,MATH_neither,Second year,"Stats_2, Stats_1",4,2,5
1,1,0.754098,0.610656,1,0,Heard_3,DSC_major,MATH_neither,Third year,Stats_2,4,3,5
2,3,0.836066,0.479508,1,1,Heard_3,DSC_major,MATH_neither,Third year,Stats_3,4,3,4
3,6,0.508197,0.200820,0,1,Heard_3,DSC_major,MATH_neither,Second year,Stats_3,3,1,4
4,9,0.672131,0.471311,1,0,Heard_3,DSC_major,MATH_major,Third year,Stats_3,4,2,4
5,11,0.918033,0.319672,1,1,Heard_3,DSC_major,MATH_neither,Second year,Stats_3,3,1,4
6,12,0.098361,0.000000,0,0,Heard_3,DSC_major,MATH_neither,Third year,Stats_3,4,4,4
7,15,0.344262,0.159836,1,1,Heard_2,DSC_major,MATH_neither,Third year (first year transfer),Stats_3,3,1,4
8,20,0.573770,0.303279,0,0,Heard_3,DSC_major,MATH_neither,Third year transfer,Stats_3,2,2,4
9,24,1.000000,0.754098,0,0,Heard_3,DSC_major,MATH_neither,Fourth year (second year transfer),"Stats_2, Stats_3, Stats_1",5,5,5
10,26,0.737705,0.442623,0,1,Heard_3,DSC_minor,MATH_major,Fourth year,Stats_3,3,2,4
11,27,0.540984,0.385246,1,1,Heard_3,DSC_major,MATH_major,Fourth year,"Stats_2, Stats_1",4,4,4
12,28,0.557377,0.286885,0,0,Heard_2,DSC_major,MATH_neither,Second year,Stats_4,2,1,3
13,29,0.672131,0.479508,1,0,Heard_3,DSC_major,MATH_neither,third year transfer,"Stats_2, Stats_1",2,2,2
14,30,0.852459,0.442623,0,1,Heard_4,DSC_major,MATH_neither,Third year,Stats_3,3,3,4
15,33,0.540984,0.311475,1,0,Heard_3,DSC_major,MATH_neither,Third year,Stats_3,4,4,5
16,38,0.721311,0.430328,0,1,Heard_3,DSC_major,MATH_neither,Fourth year (second year transfer),Stats_3,4,3,3
17,40,0.622951,0.229508,0,0,Heard_1,DSC_major,MATH_neither,First year,Stats_4,3,4,4
18,41,0.508197,0.155738,1,0,Heard_1,DSC_major,MATH_neither,First year,Stats_4,1,2,3
19,46,0.606557,0.364754,0,1,Heard_1,DSC_neither,MATH_major,First year,Stats_4,2,1,2
20,48,0.442623,0.303279,0,0,Heard_1,DSC_major,MATH_neither,First year,Stats_3,3,3,2
21,51,0.918033,0.590164,1,1,Heard_1,DSC_minor,MATH_major,First year,Stats_4,2,2,2
22,53,0.622951,0.405738,1,0,Heard_1,DSC_neither,MATH_neither,First year,Stats_4,1,1,2
23,56,0.786885,0.557377,0,0,Heard_1,DSC_major,MATH_neither,First year,Stats_4,3,4,3
24,58,0.459016,0.168033,0,1,Heard_1,DSC_major,MATH_neither,First year,Stats_4,3,4,3
25,61,1.000000,0.479508,1,0,Heard_1,DSC_neither,MATH_neither,First year,Stats_4,2,2,2
26,63,0.721311,0.196721,1,1,Heard_1,DSC_minor,MATH_neither,First year,Stats_4,4,1,3
27,64,0.868852,0.819672,0,0,Heard_4,DSC_major,MATH_major,Fourth year,"Stats_2, Stats_1",5,3,5
28,66,1.000000,0.778689,0,1,Heard_1,DSC_neither,MATH_neither,Fourth year,Stats_4,5,2,1
29,80,0.737705,0.520492,0,0,Heard_4,DSC_major,MATH_neither,Third year,"Stats_2, Stats_3",5,1,5
30,88,0.131148,-0.032787,0,0,Heard_1,DSC_minor,MATH_major,First year,Stats_4,4,4,4

In [57]:
df_encoded = pd.concat([samples, samples['stats_courses_taken'].str.get_dummies(sep=', '), 
                        samples['recruitment_source'].str.get_dummies(sep=', '),
                        samples['dsc_affiliation'].str.get_dummies(sep=', '),
                        samples['math_affiliation'].str.get_dummies(sep=', '),], axis = 1)
df_encoded = df_encoded.drop(columns = ['recruitment_source', 'dsc_affiliation', 'math_affiliation', 'stats_courses_taken', 'Stats_4',
                           'DSC_neither', 'MATH_neither'], errors='ignore') 
#dropping all string columns and neither columns to prevent redundency
df_encoded

,id,final_score,final_score_adj,coding,handwritten,class_standing,stats_confidence,chebyshev_familiarity,python_skill_level,Stats_1,Stats_2,Stats_3,Heard_1,Heard_2,Heard_3,Heard_4,DSC_major,DSC_minor,MATH_major
0,0,0.737705,0.586066,0,0,Second year,4,2,5,1,1,0,0,0,1,0,1,0,0
1,1,0.754098,0.610656,1,0,Third year,4,3,5,0,1,0,0,0,1,0,1,0,0
2,3,0.836066,0.479508,1,1,Third year,4,3,4,0,0,1,0,0,1,0,1,0,0
3,6,0.508197,0.200820,0,1,Second year,3,1,4,0,0,1,0,0,1,0,1,0,0
4,9,0.672131,0.471311,1,0,Third year,4,2,4,0,0,1,0,0,1,0,1,0,1
5,11,0.918033,0.319672,1,1,Second year,3,1,4,0,0,1,0,0,1,0,1,0,0
6,12,0.098361,0.000000,0,0,Third year,4,4,4,0,0,1,0,0,1,0,1,0,0
7,15,0.344262,0.159836,1,1,Third year (first year transfer),3,1,4,0,0,1,0,1,0,0,1,0,0
8,20,0.573770,0.303279,0,0,Third year transfer,2,2,4,0,0,1,0,0,1,0,1,0,0
9,24,1.000000,0.754098,0,0,Fourth year (second year transfer),5,5,5,1,1,1,0,0,1,0,1,0,0
10,26,0.737705,0.442623,0,1,Fourth year,3,2,4,0,0,1,0,0,1,0,0,1,1
11,27,0.540984,0.385246,1,1,Fourth year,4,4,4,1,1,0,0,0,1,0,1,0,1
12,28,0.557377,0.286885,0,0,Second year,2,1,3,0,0,0,0,1,0,0,1,0,0
13,29,0.672131,0.479508,1,0,third year transfer,2,2,2,1,1,0,0,0,1,0,1,0,0
14,30,0.852459,0.442623,0,1,Third year,3,3,4,0,0,1,0,0,0,1,1,0,0
15,33,0.540984,0.311475,1,0,Third year,4,4,5,0,0,1,0,0,1,0,1,0,0
16,38,0.721311,0.430328,0,1,Fourth year (second year transfer),4,3,3,0,0,1,0,0,1,0,1,0,0
17,40,0.622951,0.229508,0,0,First year,3,4,4,0,0,0,1,0,0,0,1,0,0
18,41,0.508197,0.155738,1,0,First year,1,2,3,0,0,0,1,0,0,0,1,0,0
19,46,0.606557,0.364754,0,1,First year,2,1,2,0,0,0,1,0,0,0,0,0,1
20,48,0.442623,0.303279,0,0,First year,3,3,2,0,0,1,1,0,0,0,1,0,0
21,51,0.918033,0.590164,1,1,First year,2,2,2,0,0,0,1,0,0,0,0,1,1
22,53,0.622951,0.405738,1,0,First year,1,1,2,0,0,0,1,0,0,0,0,0,0
23,56,0.786885,0.557377,0,0,First year,3,4,3,0,0,0,1,0,0,0,1,0,0
24,58,0.459016,0.168033,0,1,First year,3,4,3,0,0,0,1,0,0,0,1,0,0
25,61,1.000000,0.479508,1,0,First year,2,2,2,0,0,0,1,0,0,0,0,0,0
26,63,0.721311,0.196721,1,1,First year,4,1,3,0,0,0,1,0,0,0,0,1,0
27,64,0.868852,0.819672,0,0,Fourth year,5,3,5,1,1,0,0,0,0,1,1,0,1
28,66,1.000000,0.778689,0,1,Fourth year,5,2,1,0,0,0,1,0,0,0,0,0,0
29,80,0.737705,0.520492,0,0,Third year,5,1,5,0,1,1,0,0,0,1,1,0,0
30,88,0.131148,-0.032787,0,0,First year,4,4,4,0,0,0,1,0,0,0,0,1,1

In [58]:
df_encoded.columns

Index(['id', 'final_score', 'final_score_adj', 'coding', 'handwritten', 'class_standing', 'stats_confidence', 'chebyshev_familiarity', 'python_skill_level',
       'Stats_1', 'Stats_2', 'Stats_3', 'Heard_1', 'Heard_2', 'Heard_3', 'Heard_4', 'DSC_major', 'DSC_minor', 'MATH_major'],
      dtype='object')

In [59]:
res5 = smf.ols( #no heard 1 stat, no MATH_minor in the sample
    formula='final_score ~ coding*handwritten + stats_confidence + chebyshev_familiarity + python_skill_level + Stats_1 + Stats_2 + Stats_3 + Heard_2 + Heard_3 + Heard_4 + DSC_major + DSC_minor + MATH_major',
    data=df_encoded
).fit()

print(res5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            final_score   R-squared:                       0.367
Model:                            OLS   Adj. R-squared:                 -0.267
Method:                 Least Squares   F-statistic:                    0.5789
Date:                Wed, 25 Feb 2026   Prob (F-statistic):              0.850
Time:                        16:39:11   Log-Likelihood:                 9.7990
No. Observations:                  31   AIC:                             12.40
Df Residuals:                      15   BIC:                             35.35
Df Model:                          15
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.8098      0.277      2.927      0.010       0.220       1.399
coding                    0.0477      0.158      0.302      0.767      -0.289       0.385
handwritten               0.0489      0.158      0.310      0.761      -0.287       0.385
coding:handwritten        0.0709      0.249      0.284      0.780      -0.461       0.603
stats_confidence          0.0230      0.064      0.360      0.724      -0.114       0.160
chebyshev_familiarity    -0.0102      0.058     -0.175      0.864      -0.135       0.114
python_skill_level       -0.0337      0.078     -0.430      0.673      -0.200       0.133
Stats_1                   0.0980      0.262      0.374      0.713      -0.460       0.656
Stats_2                   0.0166      0.268      0.062      0.951      -0.554       0.587
Stats_3                  -0.0466      0.169     -0.276      0.786      -0.407       0.313
Heard_2                  -0.1351      0.259     -0.522      0.609      -0.686       0.416
Heard_3                   0.1147      0.232      0.494      0.628      -0.380       0.609
Heard_4                   0.3212      0.315      1.019      0.325      -0.351       0.993
DSC_major                -0.2138      0.223     -0.960      0.352      -0.688       0.261
DSC_minor                -0.1361      0.231     -0.589      0.564      -0.628       0.356
MATH_major               -0.1360      0.140     -0.968      0.348      -0.435       0.163
==============================================================================
Omnibus:                        2.095   Durbin-Watson:                   2.311
Prob(Omnibus):                  0.351   Jarque-Bera (JB):                1.237
Skew:                          -0.480   Prob(JB):                        0.539
Kurtosis:                       3.188   Cond. No.                         61.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [60]:
coeffs = pd.DataFrame({
    'coef': res5.params,
    'std_err': res5.bse,
    't': res5.tvalues,
    'p': res5.pvalues
})

print(coeffs)

                           coef   std_err         t         p
Intercept              0.809752  0.276668  2.926805  0.010413
coding                 0.047698  0.158059  0.301771  0.766970
handwritten            0.048913  0.157565  0.310433  0.760504
coding:handwritten     0.070887  0.249418  0.284212  0.780134
stats_confidence       0.023029  0.064055  0.359512  0.724223
chebyshev_familiarity -0.010201  0.058454 -0.174511  0.863798
python_skill_level    -0.033686  0.078256 -0.430463  0.672980
Stats_1                0.098043  0.261891  0.374365  0.713372
Stats_2                0.016644  0.267618  0.062192  0.951231
Stats_3               -0.046602  0.168940 -0.275850  0.786427
Heard_2               -0.135067  0.258652 -0.522194  0.609161
Heard_3                0.114653  0.232007  0.494180  0.628337
Heard_4                0.321236  0.315358  1.018641  0.324523
DSC_major             -0.213783  0.222680 -0.960047  0.352252
DSC_minor             -0.136105  0.230888 -0.589482  0.564312
MATH_major            -0.135999  0.140427 -0.968469  0.348168

## Adjusted Final Score

In [61]:
res6 = smf.ols( #no heard 1 stat, no MATH_minor in the sample
    formula='final_score_adj ~ coding*handwritten + stats_confidence + chebyshev_familiarity + python_skill_level + Stats_1 + Stats_2 + Stats_3 + Heard_2 + Heard_3 + Heard_4 + DSC_major + DSC_minor + MATH_major',
    data=df_encoded
).fit()

print(res6.summary())

#A negative adjusted R² is a warning. You probably need to:
#Reduce predictors (feature selection)
#Collect more data
#Try a different model

                            OLS Regression Results
==============================================================================
Dep. Variable:        final_score_adj   R-squared:                       0.507
Model:                            OLS   Adj. R-squared:                  0.015
Method:                 Least Squares   F-statistic:                     1.030
Date:                Wed, 25 Feb 2026   Prob (F-statistic):              0.478
Time:                        16:39:11   Log-Likelihood:                 16.116
No. Observations:                  31   AIC:                           -0.2325
Df Residuals:                      15   BIC:                             22.71
Df Model:                          15
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.4918      0.226      2.179      0.046       0.011       0.973
coding                    0.0202      0.129      0.157      0.878      -0.255       0.295
handwritten              -0.0076      0.129     -0.059      0.953      -0.282       0.266
coding:handwritten        0.0018      0.203      0.009      0.993      -0.432       0.435
stats_confidence          0.0480      0.052      0.919      0.373      -0.063       0.159
chebyshev_familiarity     0.0055      0.048      0.116      0.909      -0.096       0.107
python_skill_level       -0.0700      0.064     -1.097      0.290      -0.206       0.066
Stats_1                   0.0365      0.214      0.171      0.867      -0.419       0.492
Stats_2                   0.1801      0.218      0.825      0.422      -0.285       0.645
Stats_3                  -0.0118      0.138     -0.086      0.933      -0.306       0.282
Heard_2                   0.0209      0.211      0.099      0.922      -0.429       0.471
Heard_3                   0.1142      0.189      0.604      0.555      -0.289       0.518
Heard_4                   0.2531      0.257      0.984      0.341      -0.295       0.801
DSC_major                -0.1710      0.182     -0.941      0.361      -0.558       0.216
DSC_minor                -0.1745      0.188     -0.927      0.369      -0.576       0.227
MATH_major                0.0137      0.115      0.119      0.907      -0.230       0.258
==============================================================================
Omnibus:                        1.500   Durbin-Watson:                   1.909
Prob(Omnibus):                  0.472   Jarque-Bera (JB):                0.711
Skew:                          -0.352   Prob(JB):                        0.701
Kurtosis:                       3.237   Cond. No.                         61.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [62]:
coeffs = pd.DataFrame({
    'coef': res6.params,
    'std_err': res6.bse,
    't': res6.tvalues,
    'p': res6.pvalues
})

print(coeffs)

                           coef   std_err         t         p
Intercept              0.491774  0.225661  2.179264  0.045665
coding                 0.020180  0.128919  0.156534  0.877699
handwritten           -0.007631  0.128516 -0.059376  0.953437
coding:handwritten     0.001757  0.203435  0.008638  0.993222
stats_confidence       0.047990  0.052246  0.918546  0.372868
chebyshev_familiarity  0.005515  0.047677  0.115670  0.909448
python_skill_level    -0.070024  0.063828 -1.097063  0.289914
Stats_1                0.036528  0.213608  0.171004  0.866506
Stats_2                0.180097  0.218280  0.825073  0.422258
Stats_3               -0.011826  0.137794 -0.085824  0.932742
Heard_2                0.020923  0.210967  0.099177  0.922311
Heard_3                0.114231  0.189234  0.603648  0.555097
Heard_4                0.253055  0.257218  0.983818  0.340809
DSC_major             -0.170984  0.181626 -0.941409  0.361411
DSC_minor             -0.174491  0.188322 -0.926559  0.368824
MATH_major             0.013668  0.114538  0.119330  0.906598